Repository codingo/Reconnoitre, pull requests merged in 2018-10, with the labels that each got.

#47 Split up ping_sweeper method
  reconnoitre/ping_sweeper.py
Labels: enhancement

#49 Update file_helper to split host ranges provided as arguments
  reconnoitre/file_helper.py
Labels: enhancement, hacktoberfest

#46 Convert scan output to strings from bytes
  reconnoitre/find_dns.py
  reconnoitre/hostname_scan.py
  reconnoitre/ping_sweeper.py
  reconnoitre/service_scan.py
  reconnoitre/snmp_walk.py
Labels: bug, hacktoberfest

#56 Removed --exec
  reconnoitre/reconnoitre.py
Labels: enhancement, hacktoberfest

#57 Remove execution command help
  README.md
Labels: enhancement, hacktoberfest

#60 Remove Simple Exec functionality
  reconnoitre.py
Labels: bug, hacktoberfest

#58 Ping sweeper file handling
  find_dns.py
  ping_sweeper.py
Labels: enhancement, hacktoberfest

#63 Beginning of a proper input class
  lib/__init__.py
  lib/core/__init__.py
  lib/core/input.py
  reconnoitre.py
Labels: enhancement, hacktoberfest

#64 Restructure modules (Refactor first steps)
  assets/tank-152362_640.png
  lib/config.json
  lib/file_helper.py
  lib/find_dns.py
  lib/hostname_scan.py
  lib/ping_sweeper.py
  lib/service_scan.py
  lib/snmp_walk.py
  lib/virtual_host_scanner.py
  reconnoitre.py
Labels: enhancement, hacktoberfest

#65 Minor image reference fix
  README.md
Labels: bug, hacktoberfest

#62 Code cleanup and automated PEP8 code style check (flake8)
  .flake8
  .travis.yml
  lib/__init__.py
  lib/core/__init__.py
  lib/core/input.py
  lib/file_helper.py
  lib/find_dns.py
  lib/hostname_scan.py
  lib/ping_sweeper.py
  lib/service_scan.py
  lib/snmp_walk.py
  lib/virtual_host_scanner.py
  reconnoitre.py
  tests/validate_config.py
Labels: enhancement, hacktoberfest

#67 Added setup.py
  lib/core/__version__.py
  setup.py
Labels: enhancement, hacktoberfest

#68 Use HTTPS
  setup.py
Labels: enhancement, hacktoberfest

#70 string encode("utf-8") - Fix #69
  lib/ping_sweeper.py
Labels: bug, hacktoberfest

#72 Fix broken setup (Closes #55, changes since #67)
  MANIFEST.in
  README.md
  Reconnoitre.egg-info/PKG-INFO
  Reconnoitre.egg-info/SOURCES.txt
  Reconnoitre.egg-info/dependency_links.txt
  Reconnoitre.egg-info/entry_points.txt
  Reconnoitre.egg-info/top_level.txt
  Reconnoitre/__init__.py
  Reconnoitre/lib/__init__.py
  Reconnoitre/lib/config.json
  Reconnoitre/lib/core/__init__.py
  Reconnoitre/lib/core/__version__.py
  Reconnoitre/lib/core/input.py
  Reconnoitre/lib/file_helper.py
  Reconnoitre/lib/find_dns.py
  Reconnoitre/lib/hostname_scan.py
  Reconnoitre/lib/ping_sweeper.py
  Reconnoitre/lib/service_scan.py
  Reconnoitre/lib/snmp_walk.py
  Reconnoitre/lib/virtual_host_scanner.py
  Reconnoitre/reconnoitre.py
  Reconnoitre/wordlists/virtual-host-scanning.txt
  build/lib.linux-x86_64-2.7/Reconnoitre/__init__.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/__init__.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/config.json
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/core/__init__.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/core/__version__.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/core/input.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/file_helper.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/find_dns.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/hostname_scan.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/ping_sweeper.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/service_scan.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/snmp_walk.py
  build/lib.linux-x86_64-2.7/Reconnoitre/lib/virtual_host_scanner.py
  build/lib.linux-x86_64-2.7/Reconnoitre/reconnoitre.py
  build/lib.linux-x86_64-2.7/Reconnoitre/wordlists/virtual-host-scanning.txt
  build/lib.linux-x86_64-2.7/lib/__init__.py
  build/lib.linux-x86_64-2.7/lib/core/__init__.py
  build/lib.linux-x86_64-2.7/lib/core/__version__.py
  build/lib.linux-x86_64-2.7/lib/core/input.py
  build/lib.linux-x86_64-2.7/lib/file_helper.py
  build/lib.linux-x86_64-2.7/lib/find_dns.py
  build/lib.linux-x86_64-2.7/lib/hostname_scan.py
  build/lib.linux-x86_64-2.7/lib/ping_sweeper.py
  build/lib.linux-x86_64-2.7/lib/service_scan.py
  build/lib.linux-x86_64-2.7/lib/snmp_walk.py
  build/lib.linux-x86_64-2.7/lib/virtual_host_scanner.py
  dist/Reconnoitre-1.0-py2.7.egg
  setup.py
Labels: enhancement, hacktoberfest

#75 Fixed broken reference on older install files
  .gitignore
  setup.py
Labels: bug, hacktoberfest

#79 Update config.json
  Reconnoitre/lib/config.json
Labels: enhancement

#80 Reformat JSON
  Reconnoitre/lib/config.json
Labels: enhancement, hacktoberfest

#82 Address flake8 issues (#81 PEP8 refactor)
  Reconnoitre/lib/core/input.py
  Reconnoitre/lib/file_helper.py
  Reconnoitre/lib/find_dns.py
  Reconnoitre/lib/service_scan.py
  Reconnoitre/lib/snmp_walk.py
  Reconnoitre/lib/virtual_host_scanner.py
  Reconnoitre/reconnoitre.py
  setup.py
  tests/validate_config.py
Labels: enhancement

#84 Fixed two runtime errors due to minor syntactic errors.
  Reconnoitre/lib/file_helper.py
  Reconnoitre/lib/service_scan.py
Labels: enhancement
